## Numpy:

In [1]:
### Insatlling The library.

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
### importing the library:
import numpy as np
    

### Creating the arrays:


In [9]:
## 1-d array:

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [7]:
a.dtype  ### checking the datatype of the array.

dtype('int32')

In [8]:
a = np.array([1,2,3,'a','b'])
a

array(['1', '2', '3', 'a', 'b'], dtype='<U11')

In [10]:
a

array([1, 2, 3, 4])

In [12]:
a = np.append(a,10)    ### appending a new element into the array.
a

array([ 1,  2,  3,  4, 10, 10])

In [14]:
a = np.append(a,[10,100])   ### appending multiple elements.
a

array([  1,   2,   3,   4,  10,  10,  10, 100,  10, 100])

In [15]:
a = np.arange(1,11)   ## creating array in particular range
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a = np.arange(1,11,2)   ### range with step
a

array([1, 3, 5, 7, 9])

In [17]:
a.nbytes  ###checking memory space occupied

20

In [18]:
a.itemsize  ### checking the individual element size

4

In [20]:
len(a)   ### checking number of elements present.


5

In [21]:
a = np.append(a,[10,'a','b'])
a

array(['1', '3', '5', '7', '9', '10', 'a', 'b'], dtype='<U11')

In [22]:
a.dtype

dtype('<U11')

In [26]:
a = np.linspace(1,10,20)  ###creating the array within the given range with defined length and 
                            ###the spacing will be equal 
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [28]:
a = np.logspace(2,5,10)   ### logarithmic spacing. 
a

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [29]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [31]:
np.full(10,"Python")   ### getting a value or element in array format with in defined number of times

array(['Python', 'Python', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Python'], dtype='<U6')

In [32]:
np.full(10,"1,2")

array(['1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2',
       '1,2'], dtype='<U3')

In [35]:
np.full(10,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [39]:
np.zeros(10,dtype = int)   ### repeating the zeroes in defined number of times.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.ones(10,dtype = int)  ### repeating the ones in defined number oftimes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
np.full(10,1+2j)

array([1.+2.j, 1.+2.j, 1.+2.j, 1.+2.j, 1.+2.j, 1.+2.j, 1.+2.j, 1.+2.j,
       1.+2.j, 1.+2.j])

In [49]:
#### 2-d array --- combination of more 1-d array.

b = np.array([[1,2,3,4],[5,6,7,8],[7,8,9,0]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 9, 0]])

In [50]:
b.dtype

dtype('int32')

In [53]:
b.ndim    ### checking the dimension of the array.

2

In [52]:
a.ndim

1

In [55]:
b.shape   ### gives number of rows and columns

(3, 4)

In [56]:
a.shape

(10,)

In [57]:
b.nbytes

48

In [58]:
b.itemsize

4

In [60]:
len(b)   ### number of rows in the array.


3

In [61]:
### 3-d array ---- combination of more 2-d arrays

c = np.array([[[1,2,3,4],[5,6,7,8]],[[4,5,6,7],[0,9,8,7]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[4, 5, 6, 7],
        [0, 9, 8, 7]]])

In [63]:
len(c)  ### gives number of 2-d arrays.

2

In [66]:
c.shape    ### no_of 2-d_arrays,no_of_rows,no_of_columns.

(2, 2, 4)

In [67]:
c.nbytes

64

In [68]:
c.itemsize

4

In [69]:
c.ndim

3

In [73]:
### multi-dimensional arrays:

d = np.array([1,2,3,4,6,7],ndmin = 10)
d

array([[[[[[[[[[1, 2, 3, 4, 6, 7]]]]]]]]]])

In [71]:
d.ndim

5

### Accessing the elements from the array:



In [78]:
### 1-d array 

a = np.array([1,2,3,4,6,7,8,9])
a

array([1, 2, 3, 4, 6, 7, 8, 9])

In [79]:
a[3]

4

In [80]:
a[4:]

array([6, 7, 8, 9])

In [81]:
a[-1]

9

In [84]:
a[-1::-1]

array([9, 8, 7, 6, 4, 3, 2, 1])

In [85]:
###  2-d array:

b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [7, 8, 9, 0]])

In [86]:
b[1]

array([5, 6, 7, 8])

In [87]:
b[1:]

array([[5, 6, 7, 8],
       [7, 8, 9, 0]])

In [90]:
b[0::2]

array([[1, 2, 3, 4],
       [7, 8, 9, 0]])

In [91]:
b[0,-1]

4

In [92]:
b[0,-2:]   ### row_index,element-index

array([3, 4])

In [93]:
b[:,-1]

array([4, 8, 0])

In [94]:
b[:,0::2]

array([[1, 3],
       [5, 7],
       [7, 9]])

In [95]:
b[1,1::2]

array([6, 8])

In [96]:
#### 3-d array:



array([[list([1, 2, 3, 4]), list([5, 6, 7, 8])],
       [list([4, 5, 6, 7]), list([0, 9, 8])]], dtype=object)

In [100]:
c = np.array([[[1,2,3,4],[5,6,7,8]],[[4,5,6,7],[0,9,8,7]]])
c

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[4, 5, 6, 7],
        [0, 9, 8, 7]]])

In [101]:
c[1]

array([[4, 5, 6, 7],
       [0, 9, 8, 7]])

In [102]:
c[1,1]

array([0, 9, 8, 7])

In [103]:
c[1,1,-2:]

array([8, 7])

In [104]:
c[:,:,-2:]

array([[[3, 4],
        [7, 8]],

       [[6, 7],
        [8, 7]]])

In [107]:
c[:,-2:,-2]

array([[3, 7],
       [6, 8]])

In [108]:
c[:,:,1::2]

array([[[2, 4],
        [6, 8]],

       [[5, 7],
        [9, 7]]])

### shape of arrays:

In [109]:
### 1-d array

a.shape

(8,)

In [110]:
### 2-d array

b.shape

(3, 4)

In [111]:
### 3-d array

c.shape


(2, 2, 4)

### Reshaping of arrays:


* giving a new shape to the elements.


In [124]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
a.shape

(9,)

In [117]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [118]:
a.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [120]:
a.reshape(1,9,1)

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]])

In [122]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [125]:
a.shape

(14,)

In [126]:
a.reshape(7,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [127]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [129]:
a.reshape(2,1,7)

array([[[ 1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14]]])

In [130]:
a.reshape(7,2,1)

array([[[ 1],
        [ 2]],

       [[ 3],
        [ 4]],

       [[ 5],
        [ 6]],

       [[ 7],
        [ 8]],

       [[ 9],
        [10]],

       [[11],
        [12]],

       [[13],
        [14]]])

In [131]:
a.reshape(7,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [133]:
a.reshape(-1,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [134]:
a.reshape(-1,2,7)

array([[[ 1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14]]])

In [136]:
a = np.arange(1,10).reshape(3,3)

In [137]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])