## Numpy continuation:

### Iteration of array:

In [1]:
l = [1,2,3,4,10]


In [3]:
for i in l:
    print(i,end = " ")

1 2 3 4 10 

In [8]:
### 1-d array iteration:

import numpy as np
a = np.arange(1,10)

In [5]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
for i in a:
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

In [9]:
### 2-d array:

b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
for i in b:  ## i holds the row values
    for j in i:  ### j holds the each element in  the row.
        print(j,end = " ")

1 2 3 4 5 6 7 8 9 

In [13]:
###  3-d array:

c = a.reshape(3,1,3)
c


array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [14]:
for i in c:
    for j in i:
        for k in j:
            print(k,end = " ")

1 2 3 4 5 6 7 8 9 

In [15]:
## keyword for iterating the arrays:

for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

In [19]:
for i in np.nditer(a):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 

### Joining of arrays:

In [21]:
## 1-d array:

a = np.arange(1,20,2)
b = np.arange(20,40,2)
c = np.concatenate((a,b))
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [22]:
### 2-d array:

c = a.reshape(5,2)
d = b.reshape(5,2)
e = np.concatenate((c,d))
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19],
       [20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [23]:
### 3-d array:

c = a.reshape(2,5,1)
d = b.reshape(2,5,1)
e = np.concatenate((c,d))
e

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[20],
        [22],
        [24],
        [26],
        [28]],

       [[30],
        [32],
        [34],
        [36],
        [38]]])

###  Stastical and Math operations on arrays:


In [32]:
a = np.arange(10,30,2).reshape(2,5)
a

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [33]:
np.min(a)   ### minimum value in the array

10

In [35]:
np.max(a)   ### mqximum value in the array


28

In [36]:
np.argmin(a)   ### index value of the minimum value.

0

In [37]:
np.argmax(a) ## index value of the maximum value.

9

In [38]:
np.mean(a) ### mean of the array elements.

19.0

In [39]:
np.median(a)  ## median of the array elements.

19.0

In [40]:
np.average(a)    ## average of the array elements

19.0

In [41]:
np.var(a)    ### variance of the array elements


33.0

In [42]:
np.sum(a)   ### overall sum of all the array elements.

190

In [43]:
np.std(a)   ### standard Deviation

5.744562646538029

In [44]:
np.average(a,1)  ### geting the average row wise

array([14., 24.])

In [46]:
np.average(a,0)  ## getting the average column wise.

array([15., 17., 19., 21., 23.])

In [48]:
np.argmax(a,0)

array([1, 1, 1, 1, 1], dtype=int64)

In [51]:
### stacking :  arranging /organising in an appropriate way.

### vetical stack
### Horizantal Stack


np.vstack(a)


array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [54]:
b = np.arange(20,40,2).reshape(2,5)
b

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [55]:
np.vstack((a,b))   ### vertical stacking

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [56]:
np.hstack(a)   ## horizantal stacking

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [57]:
np.hstack((a,b))

array([[10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38]])

In [58]:
np.sum(a,1)

array([ 70, 120])

In [59]:
np.sum(a,0)

array([30, 34, 38, 42, 46])

In [60]:
np.sqrt(a)   ### square root of each element 

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069],
       [4.47213595, 4.69041576, 4.89897949, 5.09901951, 5.29150262]])

In [61]:
np.exp(a)   ### exponential of each element

array([[2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
        6.56599691e+07],
       [4.85165195e+08, 3.58491285e+09, 2.64891221e+10, 1.95729609e+11,
        1.44625706e+12]])

In [62]:
np.sin(a)   ### sin function

array([[-0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725],
       [ 0.91294525, -0.00885131, -0.90557836,  0.76255845,  0.27090579]])

In [63]:
np.cos(a)    ### cosine function

array([[-0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671],
       [ 0.40808206, -0.99996083,  0.42417901,  0.64691932, -0.96260587]])

In [64]:
np.tan(a)    ### tan function

array([[ 0.64836083, -0.63585993,  7.24460662,  0.30063224, -1.13731371],
       [ 2.23716094,  0.00885166, -2.1348967 ,  1.17875355, -0.2814296 ]])

In [65]:
np.log(a)   ### logaritham

array([[2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176],
       [2.99573227, 3.09104245, 3.17805383, 3.25809654, 3.33220451]])

In [66]:
np.log2(a)   

array([[3.32192809, 3.5849625 , 3.80735492, 4.        , 4.169925  ],
       [4.32192809, 4.45943162, 4.5849625 , 4.70043972, 4.80735492]])

In [70]:
np.remainder(a,3)

array([[1, 0, 2, 1, 0],
       [2, 1, 0, 2, 1]], dtype=int32)

In [68]:
a

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [71]:
np.degrees(a)

array([[ 572.95779513,  687.54935416,  802.14091318,  916.73247221,
        1031.32403124],
       [1145.91559026, 1260.50714929, 1375.09870831, 1489.69026734,
        1604.28182637]])

In [73]:
np.diff(a)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [77]:
np.ediff1d(a)   ### consecutive elements difference after converting into 1-d array.

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [78]:
np.i0(a)    ### bessel function

array([[       2815,       18948,      129418,      893446,     6218412],
       [   43558282,   306692993, -2147483648, -2147483648, -2147483648]])

In [79]:
np.mod(a,1)   ### modulous

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [80]:
np.power(a,2)   ###power 

array([[100, 144, 196, 256, 324],
       [400, 484, 576, 676, 784]], dtype=int32)

In [82]:
np.reciprocal(a,dtype = float)  ### reciprocal

array([[0.1       , 0.08333333, 0.07142857, 0.0625    , 0.05555556],
       [0.05      , 0.04545455, 0.04166667, 0.03846154, 0.03571429]])

In [83]:
np.multiply(a,2)   ### multiplication

array([[20, 24, 28, 32, 36],
       [40, 44, 48, 52, 56]])

In [87]:
np.divide(a,2)   ### Division

array([[ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [88]:
np.real(a)   ### real values

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [89]:
np.imag(a)   ### imaginary values

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [93]:
a = np.array([1+2j,2+3j])
a

array([1.+2.j, 2.+3.j])

In [94]:
np.real(a)

array([1., 2.])

In [95]:
np.imag(a)

array([2., 3.])

### Ravel and Flatten:

* **Ravel** :  Ravel is a function used to create a copy of original array,if we change anything in the duplicate array ,those changes will be applied to our original array.

* **Flatten** : Flatten is a function to create a copy of original array,if we change anything in the duplicate array,those changes are not applicable to the original array.


In [96]:
a = np.array([1,2,3,4,5,7,8])   ### original array
a

array([1, 2, 3, 4, 5, 7, 8])

In [97]:
duplicate = a.ravel()
duplicate

array([1, 2, 3, 4, 5, 7, 8])

In [98]:
duplicate[0] = 10

In [99]:
duplicate

array([10,  2,  3,  4,  5,  7,  8])

In [100]:
a

array([10,  2,  3,  4,  5,  7,  8])

In [101]:
### Flatten :

a    ### original array

array([10,  2,  3,  4,  5,  7,  8])

In [102]:
copy = a.flatten()

In [103]:
copy    ### copy of a array

array([10,  2,  3,  4,  5,  7,  8])

In [104]:
copy[0] = 11
copy

array([11,  2,  3,  4,  5,  7,  8])

In [105]:
a

array([10,  2,  3,  4,  5,  7,  8])

### Random Methods:

In [116]:
np.random.randint(100)   ### integer value within a given range

54

In [126]:
np.random.rand()     ### float value in the range of 0 and 1

0.6366233810273217

In [127]:
np.random.randint(100,size = (20))   ### 1-d array with defined range of elements

array([69, 24, 52, 55, 82, 56, 26, 42, 96, 17, 23, 96, 20, 25, 77, 54, 59,
       37, 47, 43])

In [128]:
np.random.randint(100,size = (3,2))   ### 2-d array

array([[89, 39],
       [65, 12],
       [47,  6]])

In [129]:
np.random.randint(100,size = (3,5,4))

array([[[76, 79, 73, 30],
        [25, 10, 35, 30],
        [51, 47, 39, 76],
        [29, 65, 29,  6],
        [78, 52, 69, 58]],

       [[27, 27, 55, 73],
        [52,  0, 59, 74],
        [94, 64, 39, 80],
        [88, 92, 28, 72],
        [95, 31, 44, 96]],

       [[47, 22,  4, 18],
        [84, 31, 55, 73],
        [94, 35, 20, 33],
        [72, 25, 44, 29],
        [95, 49,  5, 88]]])

In [130]:
np.random.rand(3,5)  ### 2-d float array

array([[0.08389832, 0.33378912, 0.57561525, 0.20956611, 0.60433963],
       [0.33599372, 0.13834072, 0.4873526 , 0.88358275, 0.77129868],
       [0.0946051 , 0.98926356, 0.66193661, 0.12521048, 0.14835532]])

In [131]:
np.random.rand(2,3,5)   ## 3-d array

array([[[0.49024016, 0.88121685, 0.55407218, 0.76614662, 0.67094594],
        [0.75201901, 0.36497133, 0.3917406 , 0.35415817, 0.86954787],
        [0.13233774, 0.25989794, 0.32274986, 0.47153395, 0.4831652 ]],

       [[0.46236296, 0.46778007, 0.41189801, 0.5910777 , 0.42334215],
        [0.7240121 , 0.16170673, 0.19718955, 0.31574466, 0.75248126],
        [0.84171536, 0.61065116, 0.58732232, 0.9870656 , 0.50459119]]])

In [145]:
np.random.choice([1,2,3,4,5,6])


4

In [147]:
np.random.choice([1,2,3,4,5,6],size = (5,3))

array([[1, 4, 4],
       [4, 1, 6],
       [5, 3, 3],
       [4, 1, 4],
       [2, 5, 3]])

In [151]:
np.random.choice([1,2,3,4,5,6],p = [0.1,0.5,0.2,0.1,0.1,0])

1

In [152]:
np.random.choice([1,2,3,4,5,6],p = [0.1,0.5,0.2,0.1,0.1,0],size = (3,3))

array([[2, 2, 2],
       [3, 2, 2],
       [5, 2, 2]])

In [160]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
np.random.shuffle(a)   ### values in the array will be shuffled

In [164]:
a

array([ 3,  4,  7,  2,  5, 10,  8,  6,  9,  1])

In [166]:
np.random.randn(10)   ### positiva and neagtive values 

array([-0.2690714 , -1.26731555,  0.52967093,  0.65833576,  0.73912254,
       -0.40104695, -0.61679585, -0.10809681, -0.39126973,  0.16949763])

In [168]:
np.random.normal(10)

9.976880717738783

In [173]:
np.random.binomial(10,p = [0.1],size = (5))

array([1, 0, 1, 0, 0])

### Array Filtering:

In [174]:
a = np.array([42,10,56,14,22])
b = [True,False,True,True,False] 
c = a[b]
c

array([42, 56, 14])

In [175]:
### print the values which are less than 22:

b = []
for i in a:
    if i<22:
        b.append(True)
    else:
        b.append(False)
c = a[b]
c


array([10, 14])

In [178]:
d = a < 22
e = a[d]
e

array([10, 14])